CREATE TABLE report_one_shot_runs (
    report_run_id TEXT PRIMARY KEY REFERENCES report_runs(report_run_id),
    input_artifact_hashes_json TEXT NOT NULL,
    input_hash TEXT NOT NULL,
    rendered_prompt_hash TEXT NOT NULL,
    actual_input_tokens INTEGER NOT NULL CHECK (actual_input_tokens > 0),
    budget_calls_reserved INTEGER NOT NULL DEFAULT 0 CHECK (budget_calls_reserved IN (0, 1)),
    budget_tokens_reserved INTEGER NOT NULL DEFAULT 0 CHECK (budget_tokens_reserved >= 0),
    processing_decisions_json TEXT NOT NULL DEFAULT '[]',
    processing_grant_ids_json TEXT NOT NULL DEFAULT '[]',
    profile TEXT NOT NULL CHECK (profile = 'stage4b_oneshot_sol'),
    model_id TEXT NOT NULL CHECK (model_id = 'gpt-5.6-sol'),
    reasoning_effort TEXT NOT NULL CHECK (reasoning_effort = 'high'),
    prompt_name TEXT NOT NULL CHECK (prompt_name = 'one-shot-report.md'),
    prompt_hash TEXT NOT NULL,
    schema_name TEXT NOT NULL CHECK (schema_name = 'one-shot-report.schema.json'),
    schema_hash TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN (
        'pending', 'running', 'complete', 'manual_required', 'failed'
    )),
    dispatch_count INTEGER NOT NULL DEFAULT 0 CHECK (dispatch_count IN (0, 1)),
    dispatch_expires_at TEXT,
    invocation_metadata_json TEXT,
    invocation_id TEXT UNIQUE,
    output_artifact_id TEXT REFERENCES artifacts(artifact_id),
    output_hash TEXT,
    error_json TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TEXT
);
